### PR TITLE
Added support for path globbing

### LINKED ISSUE #5: Feature request: More expressive file globbing
It would be convenient to specify `**/*.pdf` and or `tmp/**` in exclusions.

### LINKED ISSUE #7: Avoiding non-source files
I am trying to integrate this tool in a build system like Buildroot, which downloads, extracts and builds various FOSS components.
While just pointing trojansourcedetector to the source directory of each FOSS component, I noticed a lot of false positives due to binary (non-source) files, like images, font files, etc. 

I started using 'exclude' entries in the config file, but having to maintain such list from a generic build system is very cumbersome, as this list may change as FOSS component versions are updated.
For example, here is the exclude list for python3 itself:

        "Doc/library/hashlib-blake2-tree.png",
        "Doc/library/pathlib-inheritance.png",
        "Doc/using/win_installer.png",
        "Lib/distutils/command/wininst-14.0.exe",
        "Lib/ensurepip/_bundled/pip-21.2.3-py3-none-any.whl",
        "Lib/ensurepip/_bundled/setuptools-57.4.0-py3-none-any.whl",
        "Lib/idlelib/Icons/idle_256.png",
        "Lib/idlelib/Icons/idle.ico",
        "Lib/test/audiodata/pluck-pcm24.aiff",
        "Lib/test/audiodata/pluck-pcm24.au",
        "Lib/test/audiodata/pluck-pcm32.aiff",
        "Lib/test/audiodata/pluck-pcm32.au",
        "Mac/BuildScript/resources/background.jpg",
        "Mac/Icons/IDLE.icns",
        "Mac/Icons/PythonCompiled.icns",
        "Mac/Icons/Python Folder.icns",
        "Mac/IDLE/IDLE.app/Contents/Resources/IDLE.icns",
        "Mac/IDLE/IDLE.app/Contents/Resources/PythonCompiled.icns",
        "Mac/Resources/iconsrc/IDE.psd",
        "PC/icons/launcher.icns",
        "PC/icons/pyc.icns",
        "PC/icons/pyd.icns",
        "PC/icons/python.icns",
        "PC/icons/python.ico",
        "PC/icons/pythonw.icns",
        "PC/icons/pythonw.ico",
        "PC/icons/pythonx150.png",
        "PC/icons/setup.icns",
        "Tools/msi/bundle/SideBar.png",

A more expressive glob feature as suggested in issue #5 could perhaps help, but I wonder if there are other approaches.

Can the tool make the distinction between 'source' files and 'binary' files?
A common approach for this is to check for the presence of a null character, but for this case I think it allows for a too easy backdoor for an adversary: adding such null byte in real source code could go unnoticed too.

### PR DESCRIPTION
**Pull request by janosdebugs**
## Please describe the change you are making

This PR fixes #5 by adding a custom globbing library to match files. This library now supports the `**/` expression. It also adds defaults for common binary files to fix #7.

## Your code will be released under [the Unlicense](LICENSE.md) into the public domain for everyone to use for any purpose. Are you in the position, and are you willing to release your code under this license?

Yes

### CODE REVIEW

**Comment by janosdebugs** [comment]
@patrickdepinguin @frenchy64 can I trouble you for a review/test?

**Comment by patrickdepinguin** [comment]
Thanks for working on this!

I pulled and compiled this branch, but couldn't make it work, e.g. in Python I still see failures on e.g. JPG files, and the glob does not seem to have effect:
```
...
{"name":"bidirectional control character","file":"Mac/BuildScript/resources/background.jpg","line":7,"column":1285,"details":"Arabic Letter Mark control character"}
{"name":"bidirectional control character","file":"Mac/BuildScript/resources/background.jpg","line":81,"column":11,"details":"Arabic Letter Mark control character"}
...
```

both without config (defaults only) as with following config:

```
{
  "exclude": [
    "**/*.jpg",
    "**.jpg"
  ]
}
```

When I use an explicit path in the exclude list, "Mac/BuildScript/resources/background.jpg", it does exclude the file as expected.

While I'm not familiar with Go, I don't see any usage of the new glob.go file and its `compile` function, except in the test code glob_test.go. Is there nothing missing in the real flow?


A side remark that hit me while testing: initially I was using your Dockerfile, but for this test I switched to local compilation. As a result, the way I call the tool is different too (either via docker run or as a native application). And this changes the way the configuration file is accepted:

* in docker context, the file is expected as extra argument, and the 'entrypoint.sh' will add the `-config` prefix
* in native context, `-config config.json` is expected. Passing just `config.json` without `-config` is accepted and no warning is given.

It took me a while before I realized it, and I don't see a real reason why it should be different. I think that any docker invocation should be transparent in the way the application works. So either both with `-config` or both without. In order to allow possible future expansion of other arguments, expecting `-config` in both cases seems most logical to me.

**Comment by janosdebugs** [comment]
DUH, @patrickdepinguin you are right. I wasn't paying attention.

**Comment by janosdebugs** [comment]
@patrickdepinguin it is now fixed and the built binary should be available from the test run here: https://github.com/haveyoudebuggedit/trojansourcedetector/actions/runs/1653261851

Could you give it another test?

**Comment by patrickdepinguin** [comment]
I'm progressing through an embedded linux build, adding some more generic exclude extensions (will share result later), but now bump into something unexpected: it seems globbing is not supported as part of a filename.

In the tensorflow sources I get e.g. following hit:
```
{"name":"bidirectional control character","file":"third_party/icu/data/icu_conversion_data.c.gz.ab","line":374,"column":41,"details":"Arabic Letter Mark control character"}
{"name":"bidirectional control character","file":"third_party/icu/data/icu_conversion_data.c.gz.ag","line":83,"column":29,"details":"Right-to-Left Override control character"}
{"name":"bidirectional control character","file":"third_party/icu/data/icu_conversion_data.c.gz.ag","line":98,"column":107,"details":"Arabic Letter Mark control character"}
```

But following excludes do not ignore it:
```
"third_party/icu/data/icu_conversion_data*"
"third_party/icu/data/icu*"
```
A wildcard on the entire directory does work:
```
"third_party/icu/data/*"
```

At first I thought it'd be related to the multiple extensions of these files, but even when copying to a single extension like .c, same failure occurs.

In shell context, such wildcard inside a pathname does work.

**Comment by janosdebugs** [comment]
Interesting, I'll add these to the test cases.

**Comment by patrickdepinguin** [comment]
I now completed my build, scanning on a bunch of projects used in an embedded linux build. I had to add some package-specific excludes, but below is a list of generic extensions I added:

```
diff --git a/config.go b/config.go
index 76a6cf7..19aa113 100644
--- a/config.go
+++ b/config.go
@@ -32,23 +32,28 @@ func (c *Config) Defaults() {
 	c.Exclude = []string{
 		// Version control systems
 		".git/**",
+		".hg/**",
 
 		// Image files. Do not include SVG here.
+		"**/*.ai",
+		"**/*.bmp",
 		"**/*.gif",
 		"**/*.jpg",
 		"**/*.png",
 		"**/*.psd",
+		"**/*.icns",
 		"**/*.ico",
 
 		// Audio files.
 		"**/*.wav",
 		"**/*.mp3",
-		"**/*.png",
 		"**/*.aiff",
 		"**/*.au",
 		"**/*.ogg",
 
 		// Executable or object files
+		"**/*.a",
+		"**/*.bin",
 		"**/*.exe",
 		"**/*.so",
 		"**/*.dll",
@@ -59,9 +64,13 @@ func (c *Config) Defaults() {
 		"**/*.zip",
 		"**/*.gz",
 		"**/*.bz",
+		"**/*.bz2",
+		"**/*.lzo",
 		"**/*.z",
 		"**/*.rar",
 		"**/*.ear",
+		"**/*.xz",
+		"**/*.zstd",
 
 		// Python
 		"**/*.whl",
@@ -78,6 +87,16 @@ func (c *Config) Defaults() {
 		// Translations
 		"**/*.mo",
 		"**/*.pot",
+
+		// Fonts
+		"**/*.woff",
+		"**/*.woff2",
+
+		// Other binary formats
+		"**/*.chm",
+		"**/*.pcap",
+		"**/*.pdf",
+		"**/*.pptx",
 	}
 	c.DetectUnicode = false
 	c.Parallelism = 10
```


Aside from the issue with globbing inside a filename as mentioned above, and the fact that '.png' was listed also in audio formats as shown in above diff, there are no issues with this PR that I can see. Thanks!

**Comment by janosdebugs** [comment]
@patrickdepinguin fixed the path matching issue and added your patterns. Could you give it another try? The release should be here shortly: https://github.com/haveyoudebuggedit/trojansourcedetector/actions/runs/1657952564

**Review by patrickdepinguin — APPROVED** [review]
This works correctly for me.

**Comment by janosdebugs** [comment]
This fix has now been released in version [1.1.0](https://github.com/haveyoudebuggedit/trojansourcedetector/releases/tag/v1.1.0).

**Pull request merged**
